Add function to show picker options menu
Wolox/wolmo-utils-ios pull request #15
Opened 2018-10-23 15:59 UTC by carcos-wolox

## Summary ##

Add function to picker that shows a menu with `Photo Gallery`, `Camera` and `Cancel` options.
This function returns an `UIAlertController` that can be presented in a view controller that has a `MediaPickerService`

## Screenshots ##
<img width="214" alt="screen shot 2018-10-23 at 10 58 19 am" src="https://user-images.githubusercontent.com/42350557/47374048-aecd1a00-d6b2-11e8-96ab-a5a0f5ec5ed2.png">

2018-10-25 15:44 UTC, danielaRiesgo requested changes
I won't do it like this exactly.
You see we already have the `func presentImagePickerController(from source: UIImagePickerControllerSourceType, for media: [MediaPickerMediaType], onPermissionNotGranted: @escaping () -> Void)` public function.
I would change that so that it can receive a Set of UIImagePickerControllerSourceType. And if the array has only one element, do as we do now, and if it has more than one, then show the action sheet with the options and according to which one is chosen, then present the correct controller.
So in summary we would have something like this:
```
public protocol MediaPickerServiceType {
    var mediaSignal: Signal<MediaPickerMedia, MediaPickerServiceError> { get }

    func presentImagePickerController(from source: UIImagePickerControllerSourceType,
                                      for media: [MediaPickerMediaType],
                                      onPermissionNotGranted: @escaping () -> Void)

    func presentImagePickerController(from sources: [UIImagePickerControllerSourceType],
                                      for media: [MediaPickerMediaType],
                                      onPermissionNotGranted: @escaping () -> Void)
    
    var cameraIsAvailable: Bool { get }
}
```

2018-11-06 14:00 UTC, danielaRiesgo reviewed
Those small things and then it's approved :D

2018-11-06 14:05 UTC, danielaRiesgo commented
Also, let's make a refrence to issue #6 that is the one we are solving here.

2018-12-27 16:39 UTC, nahuelgl requested changes

2018-12-27 16:39 UTC, nahuelgl commented on Utils/Services/ImagePickerService.swift
> +                option.isPermitted().startWithResult { [unowned self] in
this block inside of the closure is exactly the same as the other method, make a function so you dont repeat code

2018-12-27 16:39 UTC, nahuelgl commented on Utils/Services/ImagePickerService.swift
> +    struct Constants {
use `static let` property directly, no need for a struct

2019-01-10 16:01 UTC, nahuelgl approved these changes

2019-02-01 16:54 UTC, nahuelgl commented
@carcos-wolox why didnt you merge this?

2019-02-01 21:45 UTC, merged